// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AuthorsNoteFormController from "./authors_note_form_controller"
application.register("authors-note-form", AuthorsNoteFormController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import ChatHotkeysController from "./chat_hotkeys_controller"
application.register("chat-hotkeys", ChatHotkeysController)

import ChatScrollController from "./chat_scroll_controller"
application.register("chat-scroll", ChatScrollController)

import ConversationChannelController from "./conversation_channel_controller"
application.register("conversation-channel", ConversationChannelController)

import CopilotController from "./copilot_controller"
application.register("copilot", CopilotController)

import CharacterImportController from "./character_import_controller"
application.register("character-import", CharacterImportController)

import LlmSettingsController from "./llm_settings_controller"
application.register("llm-settings", LlmSettingsController)

import MarkdownController from "./markdown_controller"
application.register("markdown", MarkdownController)

import MessageActionsController from "./message_actions_controller"
application.register("message-actions", MessageActionsController)

import MessageFormController from "./message_form_controller"
application.register("message-form", MessageFormController)

import PendingCharactersController from "./pending_characters_controller"
application.register("pending-characters", PendingCharactersController)

import PromptPreviewController from "./prompt_preview_controller"
application.register("prompt-preview", PromptPreviewController)

import RangeDisplayController from "./range_display_controller"
application.register("range-display", RangeDisplayController)

import SchemaRendererController from "./schema_renderer_controller"
application.register("schema-renderer", SchemaRendererController)

import SegmentedController from "./segmented_controller"
application.register("segmented", SegmentedController)

import SettingsFormController from "./settings_form_controller"
application.register("settings-form", SettingsFormController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TagsInputController from "./tags_input_controller"
application.register("tags-input", TagsInputController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import AuthorsNoteModalController from "./authors_note_modal_controller"
application.register("authors-note-modal", AuthorsNoteModalController)

import RunDetailModalController from "./run_detail_modal_controller"
application.register("run-detail-modal", RunDetailModalController)

import RunsPanelController from "./runs_panel_controller"
application.register("runs-panel", RunsPanelController)

import GroupQueueController from "./group_queue_controller"
application.register("group-queue", GroupQueueController)

import KeysInputController from "./keys_input_controller"
application.register("keys-input", KeysInputController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import LorebookEditorController from "./lorebook_editor_controller"
application.register("lorebook-editor", LorebookEditorController)

import EntryFormController from "./entry_form_controller"
application.register("entry-form", EntryFormController)

import PolicyPresetController from "./policy_preset_controller"
application.register("policy-preset", PolicyPresetController)

import PresetSelectorController from "./preset_selector_controller"
application.register("preset-selector", PresetSelectorController)

import ArrayFieldController from "./array_field_controller"
application.register("array-field", ArrayFieldController)

import CharacterPickerController from "./character_picker_controller"
application.register("character-picker", CharacterPickerController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)
