// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import ChatHotkeysController from "./chat_hotkeys_controller"
application.register("chat-hotkeys", ChatHotkeysController)

import ChatScrollController from "./chat_scroll_controller"
application.register("chat-scroll", ChatScrollController)

import ConversationChannelController from "./conversation_channel_controller"
application.register("conversation-channel", ConversationChannelController)

import CopilotController from "./copilot_controller"
application.register("copilot", CopilotController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import LlmSettingsController from "./llm_settings_controller"
application.register("llm-settings", LlmSettingsController)

import MarkdownController from "./markdown_controller"
application.register("markdown", MarkdownController)

import MessageActionsController from "./message_actions_controller"
application.register("message-actions", MessageActionsController)

import MessageFormController from "./message_form_controller"
application.register("message-form", MessageFormController)

import PendingCharactersController from "./pending_characters_controller"
application.register("pending-characters", PendingCharactersController)

import PromptPreviewController from "./prompt_preview_controller"
application.register("prompt-preview", PromptPreviewController)

import RangeDisplayController from "./range_display_controller"
application.register("range-display", RangeDisplayController)

import SchemaRendererController from "./schema_renderer_controller"
application.register("schema-renderer", SchemaRendererController)

import SegmentedController from "./segmented_controller"
application.register("segmented", SegmentedController)

import SettingsFormController from "./settings_form_controller"
application.register("settings-form", SettingsFormController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TagsInputController from "./tags_input_controller"
application.register("tags-input", TagsInputController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import AuthorsNoteModalController from "./authors_note_modal_controller"
application.register("authors-note-modal", AuthorsNoteModalController)

import RunDetailModalController from "./run_detail_modal_controller"
application.register("run-detail-modal", RunDetailModalController)

import RunsPanelController from "./runs_panel_controller"
application.register("runs-panel", RunsPanelController)
