// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ArrayFieldController from "./array_field_controller"
application.register("array-field", ArrayFieldController)

import AuthorsNoteModalController from "./authors_note_modal_controller"
application.register("authors-note-modal", AuthorsNoteModalController)

import AutoWithoutHumanToggleController from "./auto_without_human_toggle_controller"
application.register("auto-without-human-toggle", AutoWithoutHumanToggleController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import CharacterImportController from "./character_import_controller"
application.register("character-import", CharacterImportController)

import CharacterPickerController from "./character_picker_controller"
application.register("character-picker", CharacterPickerController)

import ChatHotkeysController from "./chat_hotkeys_controller"
application.register("chat-hotkeys", ChatHotkeysController)

import ChatScrollController from "./chat_scroll_controller"
application.register("chat-scroll", ChatScrollController)

import PlaygroundPersonaController from "./playground_persona_controller"
application.register("playground-persona", PlaygroundPersonaController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import ConversationChannelController from "./conversation_channel_controller"
application.register("conversation-channel", ConversationChannelController)

import AutoController from "./auto_controller"
application.register("auto", AutoController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import DetailsDropdownController from "./details_dropdown_controller"
application.register("details-dropdown", DetailsDropdownController)

import DropdownSelectController from "./dropdown_select_controller"
application.register("dropdown-select", DropdownSelectController)

import EntryFormController from "./entry_form_controller"
application.register("entry-form", EntryFormController)

import GroupQueueController from "./group_queue_controller"
application.register("group-queue", GroupQueueController)

import KeysInputController from "./keys_input_controller"
application.register("keys-input", KeysInputController)

import LlmSettingsController from "./llm_settings_controller"
application.register("llm-settings", LlmSettingsController)

import LorebookImportController from "./lorebook_import_controller"
application.register("lorebook-import", LorebookImportController)

import MarkdownController from "./markdown_controller"
application.register("markdown", MarkdownController)

import MessageActionsController from "./message_actions_controller"
application.register("message-actions", MessageActionsController)

import MessageFormController from "./message_form_controller"
application.register("message-form", MessageFormController)

import PauseToggleController from "./pause_toggle_controller"
application.register("pause-toggle", PauseToggleController)

import PendingCharactersController from "./pending_characters_controller"
application.register("pending-characters", PendingCharactersController)

import PolicyPresetController from "./policy_preset_controller"
application.register("policy-preset", PolicyPresetController)

import PresetImportController from "./preset_import_controller"
application.register("preset-import", PresetImportController)

import PresetSelectorController from "./preset_selector_controller"
application.register("preset-selector", PresetSelectorController)

import PromptPreviewController from "./prompt_preview_controller"
application.register("prompt-preview", PromptPreviewController)

import RangeDisplayController from "./range_display_controller"
application.register("range-display", RangeDisplayController)

import RunDetailModalController from "./run_detail_modal_controller"
application.register("run-detail-modal", RunDetailModalController)

import RunsPanelAutoRefreshController from "./runs_panel_auto_refresh_controller"
application.register("runs-panel-auto-refresh", RunsPanelAutoRefreshController)

import RunsPanelController from "./runs_panel_controller"
application.register("runs-panel", RunsPanelController)

import SaveIndicatorController from "./save_indicator_controller"
application.register("save-indicator", SaveIndicatorController)

import SchemaRendererController from "./schema_renderer_controller"
application.register("schema-renderer", SchemaRendererController)

import SegmentedController from "./segmented_controller"
application.register("segmented", SegmentedController)

import SettingsFormController from "./settings_form_controller"
application.register("settings-form", SettingsFormController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TagsInputController from "./tags_input_controller"
application.register("tags-input", TagsInputController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TouchSwipeController from "./touch_swipe_controller"
application.register("touch-swipe", TouchSwipeController)
