# frozen_string_literal: true

module Playgrounds
  # Controller for generating Auto suggestion candidates.
  #
  # Allows users with a human membership to generate suggested replies
  # without automatically sending them.
  #
  # @example Generate candidates
  #   POST /playgrounds/:playground_id/auto_candidates
  #
  class AutoCandidatesController < Playgrounds::ApplicationController
    include Authorization

    before_action :ensure_space_writable

    # POST /playgrounds/:playground_id/auto_candidates
    #
    # Enqueues jobs to generate candidate replies for the current user.
    # Each candidate is generated by a separate job, allowing parallel execution
    # via SolidQueue's llm queue thread pool.
    #
    # @param candidate_count [Integer] number of candidates to generate (1-4, default 1)
    # @return [JSON] generation_id for tracking the request
    def create
      user_membership = @playground.space_memberships.active.find_by(user: Current.user, kind: "human")

      # Validate user can use suggestions
      unless user_membership&.auto_capable?
        return render json: { error: "Suggestions require a human membership" }, status: :forbidden
      end

      if user_membership.auto_enabled?
        return render json: { error: "Suggestions are disabled while Auto is active" }, status: :forbidden
      end

      # Get the root conversation for this playground
      conversation = @playground.conversations.root.first
      unless conversation
        return render json: { error: "No conversation found for this playground" }, status: :not_found
      end

      # Use client-provided generation_id or generate new one
      generation_id = params[:generation_id].presence || SecureRandom.uuid
      candidate_count = (params[:candidate_count] || 1).to_i.clamp(1, 4)

      # Enqueue individual jobs for each candidate - SolidQueue will parallelize them
      # Frontend tracks completion by counting received candidates
      candidate_count.times do |index|
        AutoCandidateJob.perform_later(
          conversation.id,
          user_membership.id,
          generation_id: generation_id,
          index: index
        )
      end

      render json: { generation_id: generation_id }
    end
  end
end
