# frozen_string_literal: true

# AI responding as a human user (copilot mode).
#
# Similar to AutoTurn, but the AI acts on behalf of a human member
# who has enabled "Full Copilot" mode. The message is attributed to
# the human's membership, but generated by AI.
#
# ## Execution
#
# Same flow as AutoTurn - the distinction is mainly for:
# - Tracking/analytics (who triggered the response)
# - UI display (show "Copilot" badge)
# - Resource management (decrement copilot_remaining_steps)
#
class ConversationRun::CopilotTurn < ConversationRun
  # Always executes via RunExecutor
  def should_execute?
    true
  end

  # Override type label for clearer UI
  def type_label
    "Copilot"
  end
end
